title: Brie Bunge
description: "Objective: Design and develop experiences that bring happiness to people's lives."
url: http://briebunge.com
author:
  name: 'Brie Bunge'
  email: ''
markdown: rdiscount
permalink: pretty
highlighter: pygments
paginate: 15
paginate_path: "blog/page:num"
excerpt_separator: <!--more-->
