title: Brie Bunge
description: "Objective: Design and develop experiences that bring happiness to people's lives."
url: http://briebunge.com
author:
  name: 'Brie Bunge'
  email: ''
markdown: rdiscount
permalink: pretty
pygments: true
paginate: 5
excerpt_separator: <!--more-->
